
server.port=8080
spring.application.name=dockersubjectapi

db.url=${SPRING_DATASOURCE_URL:jdbc:mysql://host.docker.internal:3306/assessmentdb}
db.username=${SPRING_DATASOURCE_USERNAME:root}
db.password=${SPRING_DATASOURCE_PASSWORD:password}
db.driver=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

